server:
  port: 8080
  servlet:
    context-path: /VitaStore

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/EcommerceDB?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci&serverTimezone=UTC"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
mail:
    host: smtp.gmail.com
    port: 587
    username: trunghuutran2005@gmail.com
    password: hzct sqsf fmfy ndao
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

vnpay:
  tmn-code: 7X4X8515
  hash-secret: VEGRHZ0WYDTC6XFC1EWHVTFA5UEQY1DI
  pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:8080/VitaStore/vnpay/return
  ipn-url: http://localhost:8080/VitaStore/vnpay/ipn
  version: 2.1.0
  command: pay
